// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlkP9b1Tzmc9jDYk-9LPSLLPLBpxJXco',
    appId: '1:1064583989729:web:ad09052b763e2c8481aaa0',
    messagingSenderId: '1064583989729',
    projectId: 'productive-create',
    authDomain: 'productive-create.firebaseapp.com',
    storageBucket: 'productive-create.appspot.com',
    measurementId: 'G-GMR49VDCMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPFBrCqxBxdNY8qMSy3hNwDpSEKHPrKg',
    appId: '1:1064583989729:android:12349289fa8a277181aaa0',
    messagingSenderId: '1064583989729',
    projectId: 'productive-create',
    storageBucket: 'productive-create.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMFxA3USDgSnLd55F2IIWan1avxS28ysQ',
    appId: '1:1064583989729:ios:c4c6921821b8d04781aaa0',
    messagingSenderId: '1064583989729',
    projectId: 'productive-create',
    storageBucket: 'productive-create.appspot.com',
    iosBundleId: 'com.example.productiveCreate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMFxA3USDgSnLd55F2IIWan1avxS28ysQ',
    appId: '1:1064583989729:ios:a1932e7b3a653fa781aaa0',
    messagingSenderId: '1064583989729',
    projectId: 'productive-create',
    storageBucket: 'productive-create.appspot.com',
    iosBundleId: 'com.example.productiveCreate.RunnerTests',
  );
}
